# Generated by Django 3.2.5 on 2021-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210702_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
