# Generated by Django 3.2.5 on 2021-08-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210702_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField()),
                ('firstname', models.CharField(max_length=26)),
                ('lastname', models.CharField(max_length=26)),
                ('state', models.CharField(max_length=26)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.BigIntegerField()),
                ('order_note', models.CharField(max_length=150)),
                ('shipping_charges', models.IntegerField()),
                ('coupon_code', models.CharField(max_length=30)),
                ('coupon_discount', models.IntegerField()),
                ('payment_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, default=1)),
                ('feedback_note', models.TextField(null=True)),
                ('img1', models.ImageField(blank=True, upload_to='img1/')),
                ('img2', models.ImageField(blank=True, upload_to='img2/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
